### ISSUE TITLE
create a form to suggest tutorial topics

### ISSUE THREAD

**Issue by durden** [pluralsight/guides-cms#5]

**Comment by durden** [comment]
We could probably leverage github.com for this or the slack channel.  Any value in this addition? @edroman @prtkgpt thoughts?

**Comment by edroman** [comment]
Is this idea to have a form to suggest categories of tutorials, or to suggest ideas for tutorials to be written?  Either way, doesn't seem to be a huge priority in my mind, since we want to keep the category list small, and individual authors generally suggest their own topics that they're passionate about.

**Comment by durden** [comment]
I think the idea was to suggest categories and ideas for new tutorials.  I'm going to close this because many more higher priority items.
