### ISSUE TITLE
Cannot close modal on editor page

### ISSUE THREAD

**Issue by durden** [pluralsight/guides-cms#54]
Reproduce with the following:
- Write a guide
- Do not enter a title
- Click save
- Notice the modal box shows up but you cannot cancel or close it

I suspect this change is related to [this fix](https://github.com/pluralsight/guides-cms/issues/52), and I missed it.  It could be related to a merge/rebase issue with [this PR](https://github.com/pluralsight/guides-cms/pull/47).

Any ideas @paulocheque ?

**Comment by paulocheque** [comment]
Maybe both are related:
- there were one extra css: `#modal-error`. I removed it.

Also, I applied some changes to avoid other modal issues. Ideally the modal code should be before de body, outside of any element with css `position: relative, fixed etc`.

I have also figured out that Bootstrap modal uses z-index 1040 and 1050, instead of only 1050 as I checked before. So I updated the z-indexes.
